---
- name: Déploiement de la stack d'Observabilité (PLG) sur Kubernetes
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Appliquer le manifeste Kubernetes (Loki et Grafana)
      kubernetes.core.k8s:
        state: present
        src: "{{ playbook_dir }}/k8s-observability.yml"