server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml # Promtail s'en sert pour se souvenir d'où il s'est arrêté de lire

clients:
  - url: http://loki:3100/loki/api/v1/push # L'adresse de ton futur conteneur Loki

scrape_configs:
  - job_name: flask_app_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: flask-app
          # C'est ici que Docker stocke les logs des conteneurs par défaut
          __path__: /var/lib/docker/containers/*/*.log 

    pipeline_stages:
      # 1. Docker "emballe" les logs dans son propre format JSON. Cette ligne le déballe.
      - docker: {}

      # 2. Maintenant on lit LE JSON de l'Étudiant 1
      - json:
          expressions:
            # On dit à Promtail : "Cherche ces clés dans le texte et stocke-les en mémoire"
            request_id: request_id
            level: levelname
            method: method
            path: path

      # 3. On transforme ce qu'on a gardé en mémoire en "Labels" pour que Loki puisse filtrer dessus
      - labels:
          request_id:
          level:
          method: